sudo: required
language: node_js

services:
  - mongodb

node_js:
  - "0.12"

install:
  - ./build/install-openldap.sh
  - cp -v build/conf.app.js app/conf.js
  - cp -v build/conf.test.js tests/conf.js
  - npm install
  - node build/store.js

before_script:

script:
  - npm test
